#' Read the BayesTraits Stones files
#'
#' Supplied with a file path to .Stones.txt files generated by BayesTraits, this function will read the header (i.e. everything before the MCMC chains) followed by the MCMC chains and neatly format it into a table. When more than one file path is provided, it will return a list of  tables.
#'
#' @param file_path path, or vector of multiple paths to BayesTraits schedule files
#' @return returns a list of tables for BayesTraits Stones files. This includes the header, the stones and their marginal likelihood, and a table with the final marginal likelihoods.
#' @import readr tidyverse
#' @examples
#' read_bt_stones("./my_bayestraits_run.Stones.txt")


## function to read BT Stones files

### arguments:
# x: is the folder that contains one or more BayesTraits Stones files. Stones files must end with .Stones.txt

### output:
# a list containing acceptance rate information


read_bt_stones<-function(file_path){

  ## read file names
  stones_paths<-file_path
  stones_names<-str_remove_all(basename(file_path), pattern="\\.Stones\\.txt")

  ## make empty lists
  header_list<-list()
  stones_list<-list()
  marLik_list<-list()

  ##
  for(i in 1:length(stones_paths)){

    ## find 1st line of table
    first_line=grep(pattern = "^Stone No", read_lines(stones_paths[i], n_max=20))-1

    ## find last line of table
    last_line=grep(pattern = "Log marginal likelihood", read_lines(stones_paths[i]))-1

    ## get header info
    header_list[[i]]<-read_lines(stones_paths,
                                 skip = 1,
                                 n_max=first_line-1) %>%
      map_chr(~ .x %>% str_replace_all("^ +|^\t+| +$|\t$", "")) %>% # remove leading and trailing spaces
      map_chr(~ .x %>% str_replace_all("(:  )+|: - |:\t", ";")) %>% # unify column delimiter
      map_chr(~ .x %>% str_replace_all("; +|;\t+| +;|\t;", ";")) %>% # remove leading and trailing spaces
      paste0(., "\n",collapse = "\n") %>%
      read_delim(delim=";",
                 col_names = c("Parameters",stones_names[i])) %>%
      purrr::discard(~all(is.na(.)))

    ## get stones iterations
    stones_list[[i]]<-read_tsv(file = stones_paths[i],
                               skip = first_line,
                               n_max = last_line-(first_line+1),
                               col_names = TRUE)

    ## get marginal likelihood
    marLik_list[[i]]<-read_tsv(file = stones_paths[i],
                                 skip = last_line,
                               col_names = c("marLik",stones_names[i]))

  }

  ### Join header lists into a single df
  header_df<-header_list %>%
    reduce(full_join, by="Parameters") %>%
    distinct()

  ### Join marginal likelihood lists into a single df
  marLik_df<-marLik_list %>%
    reduce(full_join, by="marLik") %>%
    distinct()

  ### concatenate stones list into a single df
  names(stones_list)<-stones_names
  stones_df<-bind_rows(stones_list, .id="Run ID")


  # function output
  return(list(header=header_df,
              stones=stones_df,
              `marginal likelihood`=marLik_df))

}

