#' Read the BayesTraits log file
#'
#' Supplied with a file path to .Log.txt files generated by BayesTraits, this function will read the header (i.e. everything before the MCMC chains) followed by the MCMC chains and neatly format it into a table. When more than one file path is provided, it will return a list of tables.
#'
#' @param file_path path, or vector of multiple paths to BayesTraits Log files
#' @param read_chains logical operator whether to read the MCMC chains output. Default is set to TRUE, but can be turned off in cases when files are large, and only run settings are desired.
#' @return returns a list of tables for BayesTraits log files. This includes the MCMC chains and the header broken up into multiple tables, including the run info (header) and any settings for restrictions, priors, ancestral state reconstructions and node fossilizations and tree other settings
#' @import readr tidyverse
#' @examples
#' read_bt_log("./my_bayestraits_run.Log.txt")

##
read_bt_log<-function(file_path, read_chains=T){

  ## stop function if wrong files loaded

  if(!all(str_detect(file_path, "\\.Log\\.txt$"))){
    stop("One or more files do not have the expected '.Log.txt' extention")
  }


    ### supress tidyverse messages and warnings
    suppressMessages(suppressWarnings({

      ### read log header
      file_path<-file_path
      log_names<-str_remove_all(basename(file_path), pattern="\\.Log\\.txt")

      ## make empty lists
      header_list<-list()
      tags_list<-list()
      restrictions_list<-list()
      priors_list<-list()
      tree_list<-list()
      recon_list<-list()
      chain_list<-list()

      ## make internal function for reading subsections.
      tabulate_section<-function(file_path,first_line, last_line, col_names) {

        read_lines(file_path,
                   skip=first_line,
                   n_max=last_line-1) %>%
          map_chr(~ .x %>% str_replace_all("^ +|^\t+| +$|\t$", "")) %>% # remove leading and trailing spaces
          map_chr(~ .x %>% str_replace_all("(:  )+|: - |:\t|\t|(  )+", ";")) %>% # unify column delimiter
          map_chr(~ .x %>% str_replace_all("; +|;\t+| +;|\t;", ";")) %>% # remove leading and trailing spaces
          map_chr(~ .x %>% str_replace_all(";+", ";")) %>% # remove duplicated column breaks
          paste0(., "\n",collapse = "\n") %>%
          read_delim(delim=";",col_names = col_names) %>%
          purrr::discard(~all(is.na(.)))
      }

      # fill the empty lists with the different sections. Loop over multiple log paths
      for(i in 1:length(file_path)){

        ## get headers
        first_line=1
        last_line=grep(pattern = "^\\s+|^\\t+", read_lines(file_path[i], n_max=Inf))[1]-2 # finds first line with a space or tab as the first character, then backtraces 2.

        header_list[[i]]<-tabulate_section(file_path[i], first_line, last_line, col_names=c("Options",log_names[i]))


        ## get tags
        first_line=grep(pattern = "Tags:", read_lines(file_path[i], n_max=Inf))
        if(length(first_line)>0) {

          last_line=grep(pattern = "^\\w+", read_lines(file_path[i], skip = first_line, n_max=Inf))[1]

          tags_list[[i]]<-tabulate_section(file_path[i], first_line, last_line,
                                           col_names=c("Tag","n","Species")) %>%
            mutate(`Run ID`=log_names[i])
        }

        ## get restrictions
        first_line=grep(pattern = "Restrictions:", read_lines(file_path[i], n_max=Inf))

        if(length(first_line)>0) {
          last_line=grep(pattern = "^\\w+", read_lines(file_path[i], skip = first_line, n_max=Inf))[1]

          restrictions_list[[i]]<-tabulate_section(file_path[i], first_line, last_line,
                                                   col_names=c("Transition",log_names[i]))
        }

        ## get priors
        first_line=grep(pattern = "Prior Information:", read_lines(file_path[i], n_max=Inf))

        if(length(first_line)>0) {
          last_line=grep(pattern = "^\\w+", read_lines(file_path[i], skip = first_line, n_max=Inf))[1]

          priors_list[[i]]<-tabulate_section(file_path[i], first_line, last_line,
                                             col_names=c("Transitions",log_names[i])) %>%
            drop_na()
        }


        ## get tree info
        first_line=grep(pattern = "Tree Information", read_lines(file_path[i], n_max=Inf))

        if(length(first_line)>0) {
          last_line=grep(pattern = "^\\w+", read_lines(file_path[i], skip = first_line, n_max=Inf))[1]

          tree_list[[i]]<- tabulate_section(file_path[i], first_line, last_line,
                                            col_names=c("Parameter",log_names[i]))
        }

        ## get reconstruction/fossilisation info

        first_line=grep(pattern = "Node reconstruction / fossilisation:", read_lines(file_path[i], n_max=Inf))

        if(length(first_line)>0) {
          last_line=grep(pattern = "^\\w+", read_lines(file_path[i], skip = first_line, n_max=Inf))[1]

          recon_list[[i]]<- tabulate_section(file_path[i], first_line, last_line,
                                             col_names=c("Parameter",log_names[i])) %>%
            separate(Parameter,into=c("node", "Node", "Tag"), sep=" ") %>%
            select(-node)
        }


        ## get chain info
        if(read_chains){
          chain_list[[i]]<-read_tsv(file_path[i],
                                    skip=grep(pattern = "Iteration\\tLh", read_lines(file_path[i], n_max=Inf))-1,
                                    col_names = TRUE,
                                    na=c("",NA, "--")) %>%
            purrr::discard(~all(is.na(.)))

          # re-define columns for discrete:independent model
          if(all( c("alpha1","alpha2", "beta1","beta2") %in% colnames(chain_list[[i]]))){
            chain_list[[i]]<-chain_list[[i]] %>%
              mutate(q12=alpha2,
                     q13=alpha1,
                     q21=beta2,
                     q24=alpha1,
                     q31=beta1,
                     q34=alpha2,
                     q42=beta1,
                     q43=beta2) %>%
              select(-starts_with(c("alpha","beta")))
          }
        }


      } # end of loop for filling sections lists


      ### Join section lists into a single df
      header_df<-header_list %>% reduce(full_join, by="Options")
      restrictions_df<-restrictions_list %>% reduce(full_join, by="Transition")
      priors_df<- priors_list %>% reduce(full_join, by="Transitions")
      tree_df<-tree_list %>% reduce(full_join,by="Parameter")
      if(length(tags_list)>0) {
        tags_df<-bind_rows(tags_list) %>%
          pivot_wider(names_from = `Run ID`, values_from=`Run ID`,values_fn = ~ 1)
      }
      if(length(recon_list)>0) recon_df<-recon_list %>% reduce(full_join, by=c("Node","Tag"))


      ## add file names to chains and bind rows into a single df. The first column contains the run names
      if(read_chains){
        names(chain_list)<-log_names
        chain_df<-bind_rows(chain_list, .id="Run ID") # appends chains
      }


      #### combine all into a single list object

      ## base data (should exist for all log files)
      df_list<-list("header"=header_df,
                    "restrictions"=restrictions_df,
                    "priors"=priors_df,
                    "tree"=tree_df)

      # append optional sections
      if(length(tags_list)>0) {
        df_list<-append(df_list, list("tags"=tags_df))
      }
      if(length(recon_list)>0) {
        df_list<-append(df_list, list("recon"=recon_df))
      }
      if(read_chains){
        df_list<-append(df_list, list("chain"=chain_df))
      }


      # return final list
      return(df_list)

    })) # close warning suppression

} # close function

