#' Read the BayesTraits Schedule files
#'
#' Supplied with a file path to .Schedule.txt files generated by BayesTraits, this function will read the header (i.e. everything before the MCMC chains) followed by the MCMC chains and neatly format it into a table. When more than one file path is provided, it will return a list of  tables.
#'
#' @param file_path path, or vector of multiple paths to BayesTraits schedule files
#' @param abbrev_length number of characters to reduce log file names to, for neater visualisation. Default is 20 characters.
#' @return returns a list of tables for BayesTraits Schedule files. This includes the header and the acceptance rates table.
#' @import readr tidyverse
#' @examples
#' read_bt_schedule("./my_bayestraits_run.Schedule.txt")

read_bt_schedule<-function(file_path, abbrev_length=20){

  ## read file names
  sched_paths<-file_path
  sched_names<-str_remove_all(basename(file_path), pattern="\\.Schedule\\.txt")
  sched_names_abbr<-abbreviate(sched_names,minlength=abbrev_length)

  ## make empty lists
  header_list<-list()
  schedule_list<-list()

  ## define custom function to deal with duplicated column names
  custom_name_repair <- function(names) {
    ave(names, names, FUN = function(x) {
      if (length(x) == 1) return(x)
      paste0(x, c("", paste0("_", seq_along(x)[-1])))
    })
  }



  ## fill the empty lists with the different sections. Loop over multiple file paths
  for(i in 1:length(sched_paths)){

    ## find 1st line of table
    first_line=grep(pattern = "^Rate Tried", read_lines(sched_paths[i], n_max=20))-1

    ## get header info
    header_list[[i]]<-read_tsv(file = sched_paths[i], n_max = first_line-1, skip = 1, col_names = FALSE) %>%
      deframe()
    ##
    schedule_list[[i]]<-read_tsv(file = sched_paths[i], skip = first_line, col_names = TRUE,name_repair= custom_name_repair) %>%
      select(where(~ !all(is.na(.)) & !all(. == "")))
  }

  ## add file names to chains and bind rows into a single df
  names(header_list)<-sched_names_abbr
  header_df<-bind_rows(header_list, .id="Run ID")

  names(schedule_list)<-sched_names_abbr
  schedule_df<-bind_rows(schedule_list, .id="Run ID")


  # function output
  return(list(header=header_df,
              schedule=schedule_df))

}

