#' Read only the header of a BayesTraits log file
#'
#' Supplied with a file path to .Log.txt files generated by BayesTraits, this function will read the header and neatly format it into a table. When more than one file path is provided, it will return a list of header tables. This function is useful when there is no interest in loading the whole MCMC chains data.
#'
#' @param file_path path, or vector of multiple paths to BayesTraits Log files
#' @return returns a table or a list of tables for BayesTraits headers
#' @import readr tidyverse
#' @examples
#' read_bt_header("./my_bayestraits_run.Log.txt")

###
read_bt_header<-function(file_path){



  ### read log header
  header_list<-list()
  #log_paths<-list.files(path=dir_path, pattern="Log.txt", full.names = T)
  log_paths<-file_path
  #log_files<-basename(log_paths)

  for(i in 1:length(log_paths)){
    last_line=grep(pattern = "^\\s+|^\\t+", read_lines(log_paths[i], n_max=1000))[1]-2 # finds first line with a space or tab as the first character, then backtraces 2.

    header_list[[i]]<-read_lines(log_paths,skip = 1,
                                 n_max=last_line-1) %>%
      map_chr(~ .x %>% str_replace_all("^ +|^\t+| +$|\t$", "")) %>% # remove leading and trailing spaces
      map_chr(~ .x %>% str_replace_all("(:  )+|: - |:\t|\t", ";")) %>% # unify column delimiter
      map_chr(~ .x %>% str_replace_all("; +|;\t+| +;|\t;", ";")) %>% # remove leading and trailing spaces
      paste0(., "\n",collapse = "\n") %>%
      read_delim(delim=";", col_names = c("Options","X")) %>%
      purrr::discard(~all(is.na(.)))
  }
  # return header as a table if length=1, return headers as list of tables if length >1
  if(length(header_list)>1){
    return(header_list)
  } else {
    header_list[[1]]
    }
}

