#' Read the BayesTraits Geo Model files
#'
#' Supplied with a file path to .AncStates.txt files generated by the BayesTraits Geo Model, this function will read the nodes descriptions/definitions followed by the MCMC iterations of latitude and longitude at of each node, and neatly formats both into tables. When more than one file path is provided, it will bind the independent runs into a single dataframe with unique run IDs. This function returns a list containing the two tablestables.
#'
#' @param file_path path, or vector of multiple paths to BayesTraits AncStates files generated by the geo model
#' @return returns a list of tables for BayesTraits Geo Model files containing the node definitions and the ancestral long/lat estimations.
#' @import readr tidyverse
#' @examples
#' read_bt_geo("./my_bayestraits_run.AncStates.txt")


## function to read BT Geo Model files

### arguments:
# x: is the folder that contains one or more BayesTraits geo model files. Stones files must end with .AncStates.txt

### output:
# a list containing acceptance rate information

read_bt_geo<-function(file_path){
  
  ## read file names
  geo_paths<-file_path
  geo_names<-str_remove_all(basename(file_path), pattern="\\.AncStates\\.txt")
  
  ## make empty lists
  node_list<-list()
  anc_list<-list()
  
  ##
  for(i in 1:length(geo_paths)){
    
    ## find 1st line of node table
    first_line=grep(pattern = "^Node Name", read_lines(geo_paths[i], n_max=20))-1
    
    ## find last line of node table
    last_line=grep(pattern = "Itter", read_lines(geo_paths[i]))-1
    
    ## get node info
    node_list[[i]]<-read_lines(geo_paths,
                                 skip = 0,
                                 n_max=last_line) %>%
      map_chr(~ .x %>% str_replace_all("^ +|^\t+| +$|\t$", "")) %>% # remove leading and trailing spaces
      map_chr(~ .x %>% str_replace_all("(:  )+|: - |:\t", ";")) %>% # unify column delimiter
      map_chr(~ .x %>% str_replace_all("; +|;\t+| +;|\t;", ";")) %>% # remove leading and trailing spaces
      paste0(., "\n",collapse = "\n") %>%
      read_delim(delim="\t") %>%
      purrr::discard(~all(is.na(.))) %>%
      group_by_all() %>%
      rowwise() %>%
      reframe(Taxa=str_split(Taxa, pattern="\\t"))
    
    ## get anc iterations
    anc_list[[i]]<-read_tsv(file = geo_paths[i],
                               skip = last_line) 
    
  }
  
  ### concatenate node list into a single df
  names(node_list)<-geo_names
  node_df<-bind_rows(node_list, .id="Run ID")
  
  ### concatenate node list into a single df
  names(anc_list)<-geo_names
  anc_df<-bind_rows(anc_list, .id="Run ID")
  
  
  
  # function output
  return(list(nodes=node_df,
              anc_geo=anc_df))
  
}
