#' Render BayesTrace report
#'
#' This function generates the BayesTrace report. It requires that the user supplies a file path to a folder/directory that contains at least one .log.txt and one .Schedule.txt files generated by BayesTraits. It will also take multile such files and will also incorporate any .Stones.txt files. The .log.txt file contains information on where the traits and tree files are stored. These are also required and must be in the same location as when BayesTraits was run.
#' #'
#' @param file_path Path to BayesTraits output files. Use full path, not relative paths. Function is recursive so that it will also read files in subfolders
#' @param output_filename Custom name for BayesTrace output
#' @param chains_burnin Percent of MCMC chains to discard as burnin (default set to 0)
#' @param downsample Define how many (random) iterations to keep for plotting (reduces load, default = 10,000)
#' @return Returns a BayesTrace report as HTML file.
#' @import Rmarkdown flexdashboard scales plotly reactable coda ape visNetwork
#' @examples
#' render_bayestrace("./path/to/BayesTrace/output")

render_bayestrace<-function(file_path,output_filename="bayestrace_report",output_dir="./", chains_burnin=0,downsample=10000){


  rmd_template_path <- system.file("rmd", "bayestrace_report.Rmd", package = "bayestrace")

  rmarkdown::render(input=rmd_template_path,
                    output_file = output_filename,
                    output_dir = output_dir,
                    params = list(file_path=file_path,
                                  chains_burnin=chains_burnin,
                                  downsample=downsample,
                                  shinyfy=FALSE),
                    envir = new.env(parent = globalenv())
  )

}

