#' Render BayesTrace report
#'
#' This function generates the BayesTrace report (Quarto render). It requires that the user supplies a file path to a directory that contains at least one .log.txt and one .Schedule.txt files generated by BayesTraits. It will also take multiple such files and will also incorporate any .Stones.txt files that are found. The .log.txt file contains information on where the traits and tree files are stored and those files will also be read in. These are therefore also required and must be in the same location as when BayesTraits was run so that the relative paths remain in tact.
#' #'
#' @param file_path Path to the directory containing BayesTraits output files. This function is recursive so that it will also read files in subfolders
#' @param output_filename Custom name for BayesTrace output
#' @param chains_burnin Percent of MCMC chains to discard as burnin (default set to 0)
#' @param downsample Define how many (random) iterations to keep for plotting (reduces load, default = 10,000)
#' @return Returns a BayesTrace report as HTML file.
#' @import quarto
#' @export
#' @examples
#' render_bayestrace(file_path="./path/to/BayesTraits/output")

render_bayestrace<-function(file_path,output_filename="bayestrace_report.html", chains_burnin=0,downsample=10000){

  # check all packages required by the report template are installed
  required_pkgs <- c(
    "quarto", "scales", "tidyverse", "plotly", "reactable",
    "coda", "ape", "visNetwork", "ggraph", "igraph", "tidygraph",
    "ggtree", "scatterpie", "ggiraph", "htmlwidgets", "data.table"
  )

  missing_pkgs <- required_pkgs[!sapply(required_pkgs, requireNamespace, quietly = TRUE)]

  if(length(missing_pkgs) > 0) {
    stop(
      "The following packages are required to render the BayesTrace report but are not installed:\n",
      paste(" -", missing_pkgs, collapse = "\n"), "\n\n",
      "Install them with:\n",
      'install.packages(c(', paste0('"', missing_pkgs, '"', collapse = ", "), '))',
      call. = FALSE
    )
  }


  # Location of the installed project
  src <- system.file("qmd", package = "bayestrace")

  # Temporary location
  tmp <- tempfile("quarto-")
  dir.create(tmp)

  # Copy the entire directory
  file.copy(
    from = src,
    to = tmp,
    recursive = TRUE
  )

  # Path to the copied qmd
  report <- file.path(tmp, "qmd", "bayestrace_quarto_report.qmd")

  quarto::quarto_render(
    input = report,
    output_format = "dashboard",
    output_file = output_filename,
    execute_dir = dirname(report),
    execute_params = list(file_path     = file_path,
                          chains_burnin = chains_burnin,
                          downsample    = downsample,
                          shinyfy       = FALSE)
  )

  # Copy the report to the working directory
  file.copy(
    from=file.path(tmp, "qmd", output_filename),
    to=file.path(getwd(), output_filename),
    overwrite = TRUE
  )

  # clean up var dir
  on.exit(unlink(tmp, recursive = TRUE), add = TRUE)
  unlink(file.path(tempdir(), "quarto-params*.yml"))
}

